ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('', views.cart_detail, name="cart_detail"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('full_remove/<int:product_id>/', views.full_remove, name="full_remove"),


]

ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views

app_name ='ecommerceapp'
urlpatterns = [
    path('',views.AllProdCat,name='AllProdCat'),
    path('<slug:c_slug>/',views.AllProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail')
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include
from ecommerceapp import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home, name='home')
    path('ecommerceapp/', include('ecommerceapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include("cart.urls")),
    path('accounts/', include("accounts.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"

urlpatterns=[

    path('',views.SearchResult,name='SearchResult'),

]

ecommerceproject/cart/models.py
from django.db import models

# Create your models here.
from ecommerceapp.models import Product


class Cart(models.Model):
    cart_id=models.CharField(max_length=25,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class CartItems(models.Model):
    product =models.ForeignKey(Product,on_delete=models.CASCADE)
    cart =models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return self.product

ecommerceproject/ecommerceapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)


    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse("ecommerceapp:products_by_category",args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='product')
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created_on=models.DateTimeField(auto_now=True)
    updated_on=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse("ecommerceapp:ProdCatDetail",args=[self.category.slug,self.slug])

    def __str__(self):
            return '{}'.format(self.name)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from .models import Cart, CartItems
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save();
    try:
        cart_item = CartItems.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save();

    except CartItems.DoesNotExist:
        cart_item = CartItems.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save();
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItems.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, "cart.html", dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save();
    else:
        cart_item.delete();
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)


    cart_item.delete();
    return redirect('cart:cart_detail')

ecommerceproject/ecommerceapp/views.py
from django.http import HttpResponse
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.shortcuts import render,get_object_or_404



# Create your views here.

def AllProdCat(request, c_slug=None):
    global products
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html', {'category': c_page,'products': products})


def ProdCatDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html', {'product': product})

ecommerceproject/ecommerceapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Averia+Serif+Libre&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css' %}" >
     <link rel="stylesheet" href="{%  static 'css/custom.css' %}" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/ecommerceapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

      welcome to the cart.
 {% endblock %}
{% block title %}
Cart - Shop your Fvourate !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
         <br>
        <h1 class="text-center my_title">Your Shopping Cart is Empty</h1>
        <br>
           <p class= "text-center"> Please Click <a href="{% url 'ecommerceapp:AllProdCat' %}">Here</a> </p>
    </div>
</div>
{% else %}
     <div>
          <div class="text-center">
          <br>
            <h1 class="text-center my_title">Your Shoppig Cart</h1>
              <br>
          </div>
     </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                   <th colspan="5">Your Items</th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                   <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom image" style="width:100px;height:100px;"></a>
                </td>
            <td class="text-left">

               {{cart_item.product.name}}
               <br>
               SKU:{{cart_item.product.id}}
               <br>
               Unit Price : ${{ cart_item.product.price }}
                <br>
                QTY: {{ cart_item.quantity }}
                <br>
                <br>
                {{ cart_item.quantity }} * $ {{ cart_item.product.price }}
            </td>
            <td>${{cart_item.sub_total}}</td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <td>
                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus-square custom_icon"></i></a> &nbsp; &nbsp;
                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon">  <i class="fas fa-minus-square custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
            </td>
            {% else %}
            <td>
&nbsp;               &nbsp; <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-square custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon" ></i></a>
            </td>
            {% endif %}
            <tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
   <table class="table my_custom_table">
      <thead class="my_custom_thead">
         <tr>
            <th>
                  Checkout
            </th>
         </tr>
      </thead>
       <tbody>
         <tr>
             <td>
                   Please review your Shopping cart items before proceeding with the order payment
             </td>
         </tr>
         <tr>
             <td class="text-left">
                 Your total is <strong>${{total}}</strong>
             </td>
         </tr>
       </tbody>
    </table>
 <div class="mx-auto"><a href="{% url 'ecommerceapp:AllProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a></div>

         </div>
    </div>
<br>
{% endif %}
{% endblock %}

ecommerceproject/ecommerceapp/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
      {{ category.desc | truncatewords:155 }}
  {% else %}
      welcome to the cart.
  {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
      {{ category.name }}Shop Cart
   {% else %}
      see our collections - shop cart
   {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
       <div class="row my_row_class">
           <div class="mx-auto">
              <p> <a href="{% url 'ecommerceapp:AllProdCat' %}">Our Product Collections :-</a>{{ category.name }}</p>
           </div>
       </div>
    {% endif %}
<div class="mx-auto">
         {% if category %}
         <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" style="width:100%;">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
         {% else %}
<div>
 <center> <img class="my_image my_image_padding" src="{% static 'img/banner1.png' %}" alt="" style="width:1500px;"></center>
</div>
<br>
<div>
    <h1 class="text-center my_title">Our Products Collections</h1>
    <p class="text-justify">A product is the item offered for sale. A product can be a service or an item. It can be physical or in virtual or cyber form. Every product is made at a cost and each is sold at a price. The price that can be charged depends on the market, the quality, the marketing and the segment that is targeted. Each product has a useful life after which it needs replacement, and a life cycle after which it has to be re-invented.</p>
</div>
         {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class=" my_bottom
        _margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center " style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image"   src="{{product.image.url}}" style="height:250px;width:250px" alt="{{product.name}}" >
                </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
<div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
 </div>

    </div>
</div>
{% endblock %}

ecommerceproject/ecommerceapp/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Avodha Training. All Rights Reserved</p>
</div>

ecommerceproject/ecommerceapp/templates/header.html
{% load static %}
<div>
   <center><img src="{% static 'img/logoss.png' %}" alt="this is logo"
                 style="height:150px;width:150px;"></center>

</div>

ecommerceproject/ecommerceapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="login">

</form>

</body>
</html>

ecommerceproject/ecommerceapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<!--  <a class="navbar-brand" href="#">Navbar</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecommerceapp:AllProdCat' %}"><i class="fas fa-home"></i> <span class="sr-only">(current)</span></a>
      </li>
         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommerceapp:AllProdCat' %}">All Products</a>
                  {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
                    {% endfor %}
        </div>
         </li>
            {% if item_count > 0 %}
            <li class="nav-item">
                 <a class="nav-link" href="cart:cart_details"><i class="fas fa-cart-plus">{{item_count}}</i></a>
            </li>
            {% endif %}
        <form class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                   {% if user.is_authenticated %}
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;




                  <span class="form-control mr-sm-2 ">hai &nbsp;&nbsp;{{user.username}}</span>
					  <a href="/accounts/logout">logout</a>
					{% else %}
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  &nbsp;&nbsp;


					    <span class="form-control mr-sm-2 "><a href="/accounts/register">Register</a> </span>
                 	    <span class="form-control mr-sm-2 " ><a href="/accounts/login">login</a> </span>
					{% endif %}
              </li>
            </ul>
            </form>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search-plus"></i></button>
    </form>
  </div>
</nav>

ecommerceproject/ecommerceapp/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {{product.desc | truncatewords:155}}
{% endblock %}
{% block title %}
   {{product.name}}Shop Cart
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerceapp:AllProdCat' %}">Home</a>|<a href="{{product.category.get_url }}"></a>{{product.name}} </p>
    </div>
    <div class="container">
        <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem;">
    <img src="{{product.image.url}}" alt="{{product.name}}" style="width:100%;">
           </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
               <p class=" text-justify my_prod_text"><b> Out of Stock </b></p>
                {% else %}
               <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
                 {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerceproject/ecommerceapp/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="first_name"><br>
    <input type="text" name="last_name" placeholder="last_name"><br>
    <input type="email" name="email" placeholder="email"><br>
    <input type="password" name="password1" placeholder="password"><br>
    <input type="password" name="password2" placeholder="confirm password"><br>
    <input type="submit" value="registration"><br>
</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
     {% endfor %}
</div>
</body>
</html>

ecommerceproject/ecommerceapp/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {{product.desc | truncatewords:155}}
{% endblock %}
{% block title %}
   {{product.name}}Shop Cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search-text">You Have Searched For: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class=" my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center " style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image"   src="{{product.image.url}}" style="height:250px;width:250px" alt="{{product.name}}" >
                </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 Results found. </p>
        </div>
        {% endfor %}
    </div
{% endblock %}